<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class-upload [
    <!ELEMENT class-upload (classes)>
    <!ATTLIST class-upload operation (insert|update) "insert">
    <!ELEMENT classes (class)>
    <!ELEMENT class (activityName, startDate, startTime, locationName, trainerName, activityDuration, activityDescription)>
    <!ELEMENT activityName (#PCDATA)>
    <!ELEMENT startDate (#PCDATA)>
    <!ELEMENT startTime (#PCDATA)>
    <!ELEMENT locationName (#PCDATA)>
    <!ELEMENT trainerName (#PCDATA)>
    <!ELEMENT activityDuration (#PCDATA)>
    <!ELEMENT activityDescription (#PCDATA)>
]>
<class-upload operation="insert">
    <classes>
        <class>
            <activityName>Yoga</activityName>
            <startDate>2024-04-09</startDate>
            <startTime>08:00:00</startTime>
            <locationName>South bank</locationName>
            <trainerName>Josh user</trainerName>
            <activityDuration>60</activityDuration>
            <activityDescription>Good</activityDescription>
        </class>
    </classes>
</class-upload>
